import { Link } from "react-router-dom";
import Icon from "../../components/common/Icons";
import { farmerSeed, marketSeed } from "../portal/shared";

const values = [
  { icon: "sprout", title: "For local farmers", text: "A focused way to publish weekly stock, manage pickup windows and receive pre-orders without building a shop of their own." },
  { icon: "basket", title: "For customers", text: "Find markets and growers, reserve fresh produce and pick it up at a time that suits your market-day plan." },
  { icon: "shield", title: "A clearer marketplace", text: "Profiles, pickup information, product details and reviews are organised so the useful information stays easy to find." },
];

export default function About() {
  const spotlight = farmerSeed.find(f=>f.spotlight) || farmerSeed[0];
  const market = marketSeed[0];
  return <div>
    <section className="relative min-h-[420px] overflow-hidden"><img src="/images/marketlink-hero-farmer-v3.webp" alt="Farmer working with fresh produce at a local market" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-navy-900/80 via-navy-900/45 to-transparent"/><div className="shell relative flex min-h-[420px] items-center py-14"><div className="max-w-2xl text-white"><p className="text-xs font-black uppercase tracking-[.22em] text-leaf-200">About MarketLink</p><h1 className="mt-3 text-4xl font-black tracking-[-.035em] text-white sm:text-5xl">Bringing the farmers market online, without losing the local feel.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-white/80 sm:text-base">MarketLink keeps discovery, reservations and pickup information together while the real handover stays simple: at the market, with the farmer.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/products" className="btn bg-leaf-500 text-white hover:bg-leaf-400">Explore products</Link><Link to="/markets" className="btn border border-white/20 bg-white/10 text-white hover:bg-white/15">Explore markets</Link></div></div></div></section>

    <section className="shell py-12 sm:py-14"><div className="grid gap-5 md:grid-cols-3">{values.map(v=><div key={v.title} className="card group"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-leaf-100 text-navy-700 transition duration-300 group-hover:scale-110 group-hover:bg-leaf-200"><Icon name={v.icon} /></span><h2 className="mt-4 text-lg font-bold">{v.title}</h2><p className="mt-2 text-sm leading-7 text-stone-500">{v.text}</p></div>)}</div></section>

    <section className="shell pb-14"><div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div className="overflow-hidden rounded-[28px] border border-stone-200 bg-white shadow-sm"><div className="vip-shine h-72 overflow-hidden"><img src={spotlight.image} alt="Featured Karachi grower" className="h-full w-full object-cover transition duration-700 hover:scale-105"/></div><div className="p-6"><span className="badge bg-leaf-100 text-leaf-800">Karachi grower spotlight</span><h2 className="mt-3 text-2xl font-extrabold">{spotlight.name}</h2><p className="mt-1 font-semibold text-leaf-700">{spotlight.specialty}</p><p className="mt-3 text-sm leading-7 text-stone-500">{spotlight.bio}</p><Link to={`/farmers/${spotlight.id}`} className="btn-outline mt-5">View grower profile →</Link></div></div><div className="rounded-[28px] bg-gradient-to-br from-leaf-50 via-white to-navy-50 p-6 sm:p-7"><p className="eyebrow">Market day in Karachi</p><h2 className="mt-2 text-2xl font-extrabold">{market.name}</h2><p className="mt-2 text-sm font-semibold text-leaf-700">{market.area} · {market.day} · {market.time}</p><p className="mt-4 text-sm leading-7 text-stone-600">{market.description}</p><div className="mt-5 overflow-hidden rounded-2xl border border-white bg-white shadow-sm"><iframe title="Karachi market map" className="h-64 w-full" loading="lazy" src={`https://www.openstreetmap.org/export/embed.html?bbox=${Number(market.lng)-0.02}%2C${Number(market.lat)-0.015}%2C${Number(market.lng)+0.02}%2C${Number(market.lat)+0.015}&layer=mapnik&marker=${market.lat}%2C${market.lng}`}/></div><Link to={`/markets/${market.id}`} className="btn-primary mt-5">Open market details →</Link></div></div></section>

    <section className="bg-navy-900 py-14 text-white"><div className="shell"><div className="grid gap-5 sm:grid-cols-3">{[["25+","fresh product listings"],["4","market-day locations"],["1","simple pickup workflow"]].map(([n,t])=><div key={t} className="rounded-2xl border border-white/10 bg-white/5 p-5"><strong className="text-3xl font-black text-leaf-200">{n}</strong><p className="mt-1 text-sm text-white/65">{t}</p></div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="btn bg-leaf-500 text-white hover:bg-leaf-400">Join MarketLink</Link><Link to="/how-it-works" className="btn border border-white/15 bg-white/5 text-white hover:bg-white/10">See how it works</Link></div></div></section>
  </div>;
}
